apiVersion: v1
kind: Service
metadata:
  name: bcgossip-service
  labels:
    job: node-bcgossip
    app: bcgossip
spec:
  type: ClusterIP
  selector:
    app: bcgossip
  ports:
    - port: 5050
      targetPort: 5050
      protocol: TCP
      name: gossip-port

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bcgossip-service-monitor
  labels:
    release: prom
    app: prom
spec:
  jobLabel: job
  endpoints:
    - interval: 30s
    - port: gossip-port
  selector:
    matchLabels:
      app: bcgossip
