apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bcgossip-service-monitor
  labels:
    release: prometheus
    app: prometheus
spec:
  jobLabel: job
  endpoints:
    - interval: 30s
    - port: gossip-port
  selector:
    matchLabels:
      name: bcgossip
 
  