apiVersion: v1
kind: Service
metadata:
  name: bcgossip-service
  labels:
    job: node-bcgossip
    app: bcgossip
spec:
  type: ClusterIP
  selector:
    app: bcgossip
  ports:
    - port: 5050
      targetPort: 5050
      protocol: TCP
      name: gossip-port