apiVersion: apps/v1
kind: Deployment
metadata:
  name: bcgossip-deploy
spec:
  selector:
    matchLabels:
      run: bcgossip
  replicas: 10
  template:
    metadata:
      labels:
        run: bcgossip
    spec:
      containers:
      - name: bcgossip-cont
        image: wwiras/bcgossip2:v8
        ports:
        - containerPort: 5050
